version: '3'

services:
  app:
    build: ./server
    ports:
      - 5000:5000
    networks:
      - default
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/

  mongo:
    image: mongo:4.4.6
    volumes:
      - mongo_data:/data/db
    networks:
      - default
    restart: always
    ports:
      - 27017:27017

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_REGISTER: http://192.168.1.212:5000/auth/register
        REACT_APP_LOGIN: http://192.168.1.212:5000/auth/login
        REACT_APP_CONNECT: http://192.168.1.212:5000/chat
        REACT_APP_SENDMESSAGE: http://192.168.1.212:5000/chat
    ports:
      - 80:80
    networks:
      - default
    restart: always
    depends_on:
        - app




networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"



volumes:
  mongo_data:
    driver: local
